const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB={name:'tavlin',version:1,db:null,async open(){this.db=await new Promise((ok,no)=>{const q=indexedDB.open(this.name,this.version);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains('recipes')){const s=d.createObjectStore('recipes',{keyPath:'id'});s.createIndex('updatedAt','updatedAt')}if(!d.objectStoreNames.contains('state'))d.createObjectStore('state',{keyPath:'key'})};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});return this},store(n,m='readonly'){return this.db.transaction(n,m).objectStore(n)},req(q){return new Promise((ok,no)=>{q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})},all(){return this.req(this.store('recipes').getAll())},put(v){return this.req(this.store('recipes','readwrite').put(v))},del(id){return this.req(this.store('recipes','readwrite').delete(id))},state(key){return this.req(this.store('state').get(key))},setState(key,value){return this.req(this.store('state','readwrite').put({key,value}))}};
let recipes=[],filter='',category='הכל',installPrompt=null,cook=null,tick=null;
const uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2), lines=s=>s.split(/\n+/).map(x=>x.trim()).filter(Boolean), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}
async function refresh(){recipes=(await DB.all()).filter(x=>!x.deletedAt).sort((a,b)=>b.updatedAt-a.updatedAt)}
function layoutHome(){const last=recipes[0];return `<section class="hero"><span class="eyebrow">ספר המתכונים המשפחתי שלך</span><h1>מה מבשלים היום?</h1><p>כל המתכונים, הזיכרונות והטעמים במקום אחד. נשמרים במכשיר שלך ועובדים גם בלי אינטרנט.</p><div class="search"><input id="homeSearch" placeholder="חיפוש לפי שם או מרכיב"><button class="primary" id="homeSearchBtn">חיפוש</button></div><div class="statusbar"><div class="stat"><b>${recipes.length}</b>מתכונים</div><div class="stat"><b>${navigator.onLine?'מחובר':'לא מקוון'}</b>מצב רשת</div><div class="stat"><b>${cook?'פעיל':'פנוי'}</b>מטבח</div></div></section><section class="quick"><button data-action="new"><span>✍️</span>מתכון ידני</button><button data-action="paste"><span>📋</span>הדבקת מתכון</button><button data-action="scan"><span>📷</span>סריקת דף</button><button data-view="library"><span>📖</span>ספר המתכונים</button></section>${cook?`<div class="backupPanel"><b>יש לך בישול פעיל</b><p>${esc(cook.recipeName)} · שלב ${cook.step+1}</p><button class="primary" data-action="resume">חזרה לבישול</button></div>`:''}<div class="sectionHead"><h2>נוספו לאחרונה</h2><button data-view="library">לכל המתכונים</button></div><div class="grid">${recipes.length?recipes.slice(0,3).map(card).join(''):`<div class="empty"><div class="big">🌿</div><h2>ברוכים הבאים לתבלין</h2><p>מתחילים מהמתכון הראשון?</p><button class="primary" data-action="new">הוספה ידנית</button></div>`}</div>`}
function card(r){return `<article class="card"><div class="photo" ${r.photo?`style="background-image:url('${r.photo}')"`:''}>${r.photo?'':'🍲'}</div><div class="cardBody"><h3>${esc(r.name)}</h3><div class="meta">${esc(r.category)} · ${r.minutes||0} דקות · ${r.ingredients.length} מרכיבים</div><div class="cardActions"><button class="primary" data-cook="${r.id}">לבישול</button><button data-edit="${r.id}">פתיחה</button><button data-copy="${r.id}" title="העתקה">שיתוף</button></div></div></article>`}
function layoutLibrary(){let shown=recipes.filter(r=>(category==='הכל'||r.category===category)&&(!filter||[r.name,...r.ingredients,...r.steps].join(' ').toLowerCase().includes(filter.toLowerCase())));return `<div class="sectionHead"><div><span class="eyebrow" style="color:var(--spice)">הספר המשפחתי</span><h1>המתכונים שלי</h1></div><button class="primary" data-action="new">＋ מתכון חדש</button></div><div class="search"><input id="libSearch" value="${esc(filter)}" placeholder="חיפוש בשם, מרכיב או שלב"><button id="libSearchBtn">חיפוש</button></div><div class="chips">${['הכל','פרווה','חלבי','בשרי','קינוח','אחר'].map(x=>`<button class="chip ${category===x?'active':''}" data-category="${x}">${x}</button>`).join('')}</div><p class="muted">${shown.length} תוצאות</p><div class="grid">${shown.length?shown.map(card).join(''):`<div class="empty"><div class="big">🔎</div><h2>לא נמצאו מתכונים</h2><p>אפשר לשנות את החיפוש או להוסיף מתכון חדש.</p></div>`}</div>`}
function layoutBackup(){return `<h1>גיבוי ושיתוף</h1><p>כל המידע נשמר רק במכשיר הזה. קובץ גיבוי מאפשר להעביר או לשחזר אותו בלי חשבון ובלי שרת.</p><section class="backupPanel"><h2>גיבוי מלא</h2><p>מוריד קובץ JSON עם כל המתכונים והתמונות ועם <code>backup_version</code>.</p><button class="primary" data-action="export">הורדת גיבוי</button><button data-action="import">שחזור מגיבוי</button></section><section class="backupPanel"><h2>פרטיות ועבודה לא מקוונת</h2><p>אין חשבון, אין ענן ואין מעקב. הנתונים נשארים ב-IndexedDB בדפדפן. האפליקציה הסטטית נשמרת במטמון ועובדת ללא רשת.</p><div class="notice">מחיקת נתוני הדפדפן תמחק גם את המתכונים המקומיים. מומלץ להוריד גיבוי אחרי שינויים חשובים.</div></section><section class="backupPanel"><h2>עוזר חכם</h2><p>העוזר החכם אינו זמין כרגע. כל שמירה, חיפוש ובישול ממשיכים לעבוד כרגיל.</p></section>`}
async function render(view=location.hash.slice(1)||'home'){if(!['home','library','backup'].includes(view))view='home';location.hash=view;$('#app').innerHTML=view==='home'?layoutHome():view==='library'?layoutLibrary():layoutBackup();bind()}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));$$('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.());$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));$$('[data-cook]').forEach(b=>b.onclick=()=>startCook(b.dataset.cook));$$('[data-copy]').forEach(b=>b.onclick=()=>shareRecipe(b.dataset.copy));$$('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;render('library')});$('#homeSearchBtn')?.addEventListener('click',()=>{filter=$('#homeSearch').value;render('library')});$('#libSearchBtn')?.addEventListener('click',()=>{filter=$('#libSearch').value;render('library')})}
const actions={new:()=>openEditor(),paste:()=>{$('#pasteDialog').showModal()},scan:()=>{$('#scanDialog').showModal()},export:exportBackup,import:()=>$('#importFile').click(),resume:()=>showCook()};
function closeDialogs(){ $$('dialog [data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close())}closeDialogs();
async function openEditor(id,seed){const f=$('#recipeForm');f.reset();f.id.value='';$('#deleteRecipe').hidden=true;let r=id?recipes.find(x=>x.id===id):seed;if(r){f.id.value=r.id||'';f.name.value=r.name||'';f.category.value=r.category||'אחר';f.minutes.value=r.minutes||30;f.ingredients.value=(r.ingredients||[]).join('\n');f.steps.value=(r.steps||[]).join('\n');f.notes.value=r.notes||'';$('#deleteRecipe').hidden=!r.id;$('#formTitle').textContent=r.id?'עריכת מתכון':'בדיקת המתכון'}else{const d=await DB.state('draft');if(d?.value){Object.entries(d.value).forEach(([k,v])=>{if(f[k])f[k].value=v})}$('#formTitle').textContent='מתכון חדש'}$('#recipeDialog').showModal()}
let draftDelay;$('#recipeForm').addEventListener('input',()=>{clearTimeout(draftDelay);draftDelay=setTimeout(()=>{const f=$('#recipeForm');DB.setState('draft',{name:f.name.value,category:f.category.value,minutes:f.minutes.value,ingredients:f.ingredients.value,steps:f.steps.value,notes:f.notes.value})},300)});
$('#recipeForm').onsubmit=async e=>{e.preventDefault();const f=e.target,id=f.id.value||uid(),old=recipes.find(x=>x.id===id);let photo=old?.photo||'';if(f.photo.files[0])photo=await fileData(f.photo.files[0]);const r={id,name:f.name.value.trim(),category:f.category.value,minutes:+f.minutes.value||0,ingredients:lines(f.ingredients.value),steps:lines(f.steps.value),notes:f.notes.value.trim(),photo,source:old?.source||'manual',sourceImage:old?.sourceImage||'',createdAt:old?.createdAt||Date.now(),updatedAt:Date.now(),favorite:old?.favorite||false};if(!r.name||!r.ingredients.length||!r.steps.length)return toast('צריך שם, מרכיבים ושלבים');await DB.put(r);await DB.setState('draft',null);$('#recipeDialog').close();await refresh();render('library');toast('המתכון נשמר במכשיר')};
$('#deleteRecipe').onclick=async()=>{const id=$('#recipeForm').id.value;if(!id)return;const r=recipes.find(x=>x.id===id);r.deletedAt=Date.now();r.updatedAt=Date.now();await DB.put(r);$('#recipeDialog').close();await refresh();render('library');toast('המתכון הועבר למחיקה');setTimeout(()=>{const t=$('#toast');t.innerHTML='המתכון נמחק · <button id="undo">ביטול</button>';t.classList.add('show');$('#undo').onclick=async()=>{delete r.deletedAt;await DB.put(r);await refresh();render('library');toast('המתכון שוחזר')}},50)};
function parseText(raw){const a=lines(raw);let name=a.shift()||'מתכון חדש',i=a.findIndex(x=>/מרכיבים|מצרכים/.test(x)),s=a.findIndex(x=>/אופן|הכנה|שלבים/.test(x));let ingredients,steps;if(i>=0&&s>i){ingredients=a.slice(i+1,s);steps=a.slice(s+1)}else{const cut=Math.max(1,Math.floor(a.length/2));ingredients=a.slice(0,cut);steps=a.slice(cut)}return{name,category:'אחר',minutes:30,ingredients,steps,notes:''}}
$('#pasteForm').onsubmit=e=>{e.preventDefault();const p=parseText(e.target.raw.value);$('#pasteDialog').close();openEditor(null,p)};
$('#scanForm').scan.onchange=async e=>{const f=e.target.files[0];if(f){$('#scanPreview').src=await fileData(f);$('#scanPreview').hidden=false}};
$('#scanForm').onsubmit=async e=>{e.preventDefault();const p=parseText(e.target.raw.value);p.source='scan';p.sourceImage=$('#scanPreview').src;$('#scanDialog').close();openEditor(null,p)};
function fileData(f){return new Promise((ok,no)=>{if(f.size>6e6)return no(toast('הקובץ גדול מדי - עד 6MB'));const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
async function startCook(id){const r=recipes.find(x=>x.id===id);cook={recipeId:id,recipeName:r.name,step:0,startedAt:Date.now(),timerTarget:null,timerMinutes:5};await DB.setState('cook',cook);showCook()}
function showCook(){const r=recipes.find(x=>x.id===cook?.recipeId);if(!r){cook=null;return}const n=r.steps.length,step=Math.min(cook.step,n-1),remaining=cook.timerTarget?Math.ceil((cook.timerTarget-Date.now())/1000):null;$('#cookContent').innerHTML=`<div class="cookTop"><div><span class="eyebrow" style="color:var(--spice)">מצב בישול</span><h2>${esc(r.name)}</h2></div><button id="closeCook">✕</button></div><div class="progress"><i style="width:${((step+1)/n)*100}%"></i></div><p class="muted">שלב ${step+1} מתוך ${n}</p><div class="step">${esc(r.steps[step])}</div><div class="timerBox"><b>טיימר לשלב</b><div class="row"><input id="timerMin" type="number" min="1" max="180" value="${cook.timerMinutes||5}"><button class="primary" id="timerStart">הפעלת טיימר</button></div>${remaining!==null?`<div class="timerTime" id="timerTime">${formatTimer(remaining)}</div>`:''}</div><div class="row"><button id="prevStep" ${step===0?'disabled':''}>הקודם</button><button class="primary" id="nextStep">${step===n-1?'סיום הבישול':'השלב הבא'}</button></div>`;$('#cookDialog').showModal();$('#closeCook').onclick=()=>$('#cookDialog').close();$('#prevStep').onclick=()=>updateCook({step:step-1});$('#nextStep').onclick=async()=>{if(step===n-1){cook=null;clearInterval(tick);await DB.setState('cook',null);$('#cookDialog').close();toast('בתיאבון! הבישול נשמר כהושלם');render('home')}else updateCook({step:step+1})};$('#timerStart').onclick=()=>{const m=+$('#timerMin').value||5;updateCook({timerMinutes:m,timerTarget:Date.now()+m*60000})};clearInterval(tick);tick=setInterval(updateTimer,1000)}
async function updateCook(x){Object.assign(cook,x);await DB.setState('cook',cook);showCook()}function updateTimer(){if(!cook?.timerTarget)return;const n=Math.ceil((cook.timerTarget-Date.now())/1000),el=$('#timerTime');if(el){el.textContent=formatTimer(n);if(n<=0)el.style.color='var(--danger)'}}function formatTimer(n){if(n<0)return `הטיימר הסתיים לפני ${Math.ceil(-n/60)} דקות`;return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
async function shareRecipe(id){const r=recipes.find(x=>x.id===id),text=`${r.name}\n\nמרכיבים:\n${r.ingredients.join('\n')}\n\nאופן הכנה:\n${r.steps.join('\n')}\n\nנשלח מתבלין`;try{await navigator.clipboard.writeText(text);toast('המתכון הועתק ואפשר לשתף אותו')}catch{download(new Blob([text],{type:'text/plain'}),`${r.name}.txt`)}}
async function exportBackup(){const data={app:'tavlin',backup_version:1,exported_at:new Date().toISOString(),recipes:await DB.all()};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`tavlin-backup-${new Date().toISOString().slice(0,10)}.json`);toast('הגיבוי הורד')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.app!=='tavlin'||!Array.isArray(data.recipes)||data.backup_version>1)throw 0;for(const r of data.recipes)if(r.id&&r.name&&Array.isArray(r.ingredients)&&Array.isArray(r.steps))await DB.put(r);await refresh();render('library');toast(`${data.recipes.length} מתכונים שוחזרו`)}catch{toast('קובץ הגיבוי אינו תקין')}e.target.value=''};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}};
window.addEventListener('hashchange',()=>render());window.addEventListener('online',()=>render());window.addEventListener('offline',()=>render());
(async()=>{await DB.open();await refresh();cook=(await DB.state('cook'))?.value||null;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render()})();
