const JSON_HEADERS={'content-type':'application/json;charset=UTF-8','cache-control':'no-store'};
const reply=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
const enc=new TextEncoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function hashPassword(password,salt=crypto.getRandomValues(new Uint8Array(16))){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},key,256);return `pbkdf2$210000$${b64(salt)}$${b64(bits)}`}
async function verifyPassword(password,stored){const [kind,n,salt,want]=stored.split('$');if(kind!=='pbkdf2')return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const got=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:+n,hash:'SHA-256'},key,256)), exp=unb64(want);if(got.length!==exp.length)return false;let d=0;for(let i=0;i<got.length;i++)d|=got[i]^exp[i];return d===0}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',key,enc.encode(value))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function session(user,env){const exp=Date.now()+7*864e5,body=`${user.id}.${exp}`,sig=await sign(body,env.SESSION_SECRET);return `${body}.${sig}`}
async function auth(req,env){const c=req.headers.get('cookie')||'',token=c.match(/(?:^|; )tavlin_session=([^;]+)/)?.[1];if(!token)return null;const [id,exp,sig]=token.split('.');if(!id||+exp<Date.now()||await sign(`${id}.${exp}`,env.SESSION_SECRET)!==sig)return null;return env.DB.prepare('SELECT id,username FROM users WHERE id=?').bind(id).first()}
const recipeFields=r=>({id:r.id||crypto.randomUUID(),name:String(r.name||'').trim(),category:String(r.category||'אחר'),minutes:Math.max(0,Math.min(1440,+r.minutes||0)),ingredients:Array.isArray(r.ingredients)?r.ingredients.map(String):[],steps:Array.isArray(r.steps)?r.steps.map(String):[],notes:String(r.notes||''),photo_key:r.photo_key||null,source:String(r.source||'manual'),updated_at:Date.now()});
export default {async fetch(req,env){const url=new URL(req.url),p=url.pathname;try{
 if(p==='/api/health')return reply({ok:true,service:'tavlin',storage:'d1'});
 if(p==='/api/setup'&&req.method==='POST'){if(await env.DB.prepare('SELECT count(*) n FROM users').first().then(x=>x.n))return reply({error:'setup_closed'},403);const b=await req.json();if(b.username!=='יוני'||typeof b.password!=='string'||b.password.length<12)return reply({error:'invalid_setup'},400);const id=crypto.randomUUID(),hash=await hashPassword(b.password);await env.DB.prepare('INSERT INTO users(id,username,password_hash,created_at) VALUES(?,?,?,?)').bind(id,b.username,hash,Date.now()).run();return reply({ok:true})}
 if(p==='/api/login'&&req.method==='POST'){const b=await req.json(),u=await env.DB.prepare('SELECT id,username,password_hash FROM users WHERE username=?').bind(String(b.username||'')).first();if(!u||!await verifyPassword(String(b.password||''),u.password_hash))return reply({error:'invalid_credentials'},401);const token=await session(u,env);return reply({ok:true,user:{username:u.username}},200,{'set-cookie':`tavlin_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=604800`})}
 if(p==='/api/logout'&&req.method==='POST')return reply({ok:true},200,{'set-cookie':'tavlin_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});
 const u=await auth(req,env);if(!u)return reply({error:'unauthorized'},401);
 if(p==='/api/me')return reply({user:{username:u.username}});
 if(p==='/api/recipes'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT id,name,category,minutes,ingredients,steps,notes,source,created_at,updated_at FROM recipes WHERE user_id=? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 500').bind(u.id).all();return reply({recipes:rows.results.map(r=>({...r,ingredients:JSON.parse(r.ingredients),steps:JSON.parse(r.steps)}))})}
 if(p==='/api/recipes'&&req.method==='POST'){const r=recipeFields(await req.json());if(!r.name||!r.ingredients.length||!r.steps.length)return reply({error:'invalid_recipe'},400);await env.DB.prepare('INSERT INTO recipes(id,user_id,name,category,minutes,ingredients,steps,notes,source,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(r.id,u.id,r.name,r.category,r.minutes,JSON.stringify(r.ingredients),JSON.stringify(r.steps),r.notes,r.source,r.updated_at,r.updated_at).run();return reply({recipe:r},201)}
 const m=p.match(/^\/api\/recipes\/([a-zA-Z0-9-]+)$/);if(m&&req.method==='PUT'){const old=await env.DB.prepare('SELECT * FROM recipes WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(m[1],u.id).first();if(!old)return reply({error:'not_found'},404);const r=recipeFields({...await req.json(),id:m[1]});if(!r.name||!r.ingredients.length||!r.steps.length)return reply({error:'invalid_recipe'},400);await env.DB.batch([env.DB.prepare('INSERT INTO recipe_versions(id,recipe_id,user_id,snapshot,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),m[1],u.id,JSON.stringify(old),Date.now()),env.DB.prepare('UPDATE recipes SET name=?,category=?,minutes=?,ingredients=?,steps=?,notes=?,source=?,updated_at=? WHERE id=? AND user_id=?').bind(r.name,r.category,r.minutes,JSON.stringify(r.ingredients),JSON.stringify(r.steps),r.notes,r.source,r.updated_at,m[1],u.id)]);return reply({recipe:r})}
 if(m&&req.method==='DELETE'){const x=await env.DB.prepare('UPDATE recipes SET deleted_at=?,updated_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(Date.now(),Date.now(),m[1],u.id).run();return x.meta.changes?reply({ok:true}):reply({error:'not_found'},404)}
 if(p==='/api/backup') {const rows=await env.DB.prepare('SELECT * FROM recipes WHERE user_id=?').bind(u.id).all();return reply({app:'tavlin',backup_version:1,exported_at:new Date().toISOString(),recipes:rows.results})}
 return reply({error:'not_found'},404)
 }catch(e){console.log('request_failed',crypto.randomUUID());return reply({error:'request_failed'},500)}}};
